title: ParkSafe
description: Privacy-focused parking assistance for NYC
remote_theme: jekyll/minima
minima:
  skin: dark

header_pages:
  - support.md

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-remote-theme

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
