// The port must match the iOS app exactly. fixtures/restriction-cases.json is generated by running
// the app's own Swift code (ParkSafe repo: Tools/RestrictionFixtures) over real and edge-case
// signs at moments that include both daylight-saving changes.
import { describe, expect, it } from 'vitest';
import type { AspCalendar } from './asp';
import { durationInfo, signStatus } from './calculator';
import cases from './fixtures/restriction-cases.json';
import { toSign, type SignFeature } from './sign';

interface Outcome {
  status: string;
  minutes?: number;
  color: string;
  text?: string;
}

const instants = cases.instants.map((iso) => Date.parse(iso));
// ASP suspensions and school closures, as the generator builds its 311 calendar
const calendar: AspCalendar = new Map(
  [...new Set([...cases.aspSuspended, ...cases.schoolsClosed])].map((date) => {
    const suspended = cases.aspSuspended.includes(date);
    return [
      date,
      {
        date,
        status: suspended ? ('suspended' as const) : ('inEffect' as const),
        ...(suspended ? { exceptionName: 'Test Holiday' } : {}),
        ...(cases.schoolsClosed.includes(date) ? { schoolsOpen: false } : {}),
      },
    ];
  }),
);

function outcome(sign: ReturnType<typeof toSign>, at: number, withAsp: boolean): Outcome {
  const status = signStatus(sign.windows, at, withAsp ? { category: sign.category, calendar } : {});
  const info = durationInfo(status);
  return {
    status: status.kind,
    ...('minutes' in status && status.minutes !== undefined ? { minutes: status.minutes } : {}),
    color: info.color,
    ...(info.text !== undefined ? { text: info.text } : {}),
  };
}

describe('restriction status matches the iOS app', () => {
  it('covers enough cases to mean something', () => {
    expect(cases.signs.length).toBeGreaterThan(50);
    expect(instants.length).toBeGreaterThan(15);
  });

  for (const signCase of cases.signs) {
    const feature = signCase.feature as unknown as SignFeature;
    const label = feature.properties.sign_description ?? signCase.id;

    it(label, () => {
      const sign = toSign(feature);
      expect(sign.id).toBe(signCase.id);
      expect([...sign.slots].sort((a, b) => a - b)).toEqual(signCase.slots);

      instants.forEach((at, i) => {
        const where = `${cases.instants[i]}`;
        expect(outcome(sign, at, false), where).toEqual(signCase.outcomes[i]);
        expect(outcome(sign, at, true), `${where} with ASP`).toEqual(signCase.outcomesWithASP[i]);
      });
    });
  }
});
